Transit work leisure
HSLdevcom/helmet-model-system pull request #183
Opened 2020-07-02 14:28 UTC by atte-wsp

Enabling separate assignment of transit work and leisure. The assignments are performed in sequence so this probably increases the model running time. However, separating work / leisure could be beneficial to improve two issues found in model testing:

1) Expansion of 24h transit volumes underestimates the volumes of trunk network (frequent service during evenings and early morning). This model has different coefficients for work and leisure that might help this issue, because work and leisure trips have different spatial distribution.
2) Transfer penalties and number of transfers per trip are overestimated. This leads to number of boardings to be clearly overestimated. This change could help because work trips have almost double the amount of transfers when comparing to leisure trips (HSL 2015: Selvitys joukkoliikenteen vaihtovastuksesta) and the change enables to use different penalties for different trip purposes. 

These however have not yet been tested.

2020-07-02 15:06 UTC, atte-wsp commented
Update: I'll perform few test runs in July to see if results will get substantially better when increasing the transfer penalty for leisure trips.

2020-08-19 06:45 UTC, zptro requested changes
Looking forward to seeing results from this one! But first we need to fix some things:

Need to update test matrices to include new assignment classes.

Need to update this with new parameter or remove the parameter altogether: https://github.com/HSLdevcom/helmet-model-system/blob/9d7ec8ac68b4579b086248dc05e876293d0bcbbf/Scripts/assignment/mock_assignment.py#L86

2020-08-19 06:45 UTC, zptro commented on Scripts/assignment/emme_assignment.py
> +    def calc_transit_cost(self, transit_class, fares, peripheral_cost, default_cost=None):
Parameter `transit_class` is overwritten in for-loop, so it does not have any effect.

2020-08-19 06:45 UTC, zptro commented on Scripts/modelsystem.py
> +                self.ass_model.calc_transit_cost(transit_class, self.zdata_forecast.transit_zone, peripheral_cost, fixed_cost)
I think this is overkill. Path choices probably do not vary that much over assignment classes that it affect transit fares in any substantial way. Takes long time to run. We could use the same matrix in both classes.

2020-08-19 06:45 UTC, zptro commented on Scripts/assignment/emme_assignment.py
> +                    day_attr += segments_attr[tp][segment.id] * param.volume_factors["transit"][tp]
Need to use the class-specific volume factor

2020-08-24 12:20 UTC, zptro commented on Scripts/assignment/emme_assignment.py
> +    def calc_transit_cost(self, transit_class, fares, peripheral_cost, default_cost=None):
https://github.com/HSLdevcom/helmet-model-system/pull/183/commits/4b645a943f21dc623b5eb6f558222759a203acd2

2020-08-24 12:21 UTC, zptro commented on Scripts/modelsystem.py
> +                self.ass_model.calc_transit_cost(transit_class, self.zdata_forecast.transit_zone, peripheral_cost, fixed_cost)
https://github.com/HSLdevcom/helmet-model-system/pull/183/commits/4b645a943f21dc623b5eb6f558222759a203acd2

2020-08-24 12:28 UTC, zptro commented on Scripts/assignment/emme_assignment.py
> +                    day_attr += segments_attr[tp][segment.id] * param.volume_factors["transit"][tp]
https://github.com/HSLdevcom/helmet-model-system/pull/183/commits/70c6f395516fb2ed37dcf23108fee46d36f0525d

2020-08-25 04:58 UTC, zptro approved these changes

2020-09-09 11:20 UTC, merged