Fix share of detached houses of new dwellings
HSLdevcom/helmet-model-system pull request #190
Opened 2020-08-25 12:32 UTC by zptro

2020-08-25 13:39 UTC, atte-wsp requested changes
This still throws error. Some zones in MAL2019 forecasts (for example id 1051) have substantial growth in share of detached houses even if population growth is close to zero. In these cases `share_detached_houses_new` can get values greater than one. 

I think here the error is in input data, which should not have changes in share of detached houses if population stays same.

2020-08-31 07:31 UTC, zptro commented
> 
> 
> This still throws error. Some zones in MAL2019 forecasts (for example id 1051) have substantial growth in share of detached houses even if population growth is close to zero. In these cases `share_detached_houses_new` can get values greater than one.
> 
> I think here the error is in input data, which should not have changes in share of detached houses if population stays same.

Thank you for observing this! I think we will have to allow these kind of input data, because in some cases land development might involve destruction of existing buildings. Even if some detached houses are replaced by more dense development, population density in existing buildings often decreases gradually. There is no easy way to model this correctly in the current framework, but I think allowing `share_detached_houses_new` to go below zero or above one wuold be an ok approximation.

2020-08-31 07:45 UTC, atte-wsp commented
I agree on previous reasoning.

2020-08-31 07:46 UTC, atte-wsp approved these changes

2020-08-31 07:50 UTC, merged