Fix/noise zones
HSLdevcom/helmet-model-system pull request #450
Opened 2022-03-14 12:44 UTC by johpiip

Fixes #449

2022-03-15 08:50 UTC, zptro requested changes
The problem could be solved by setting `traffic` to at least 0.01 here:

https://github.com/HSLdevcom/helmet-model-system/blob/f43f167ca5caae9aa2ee776e9b35c9b46d19a37f/Scripts/utils/calc_noise.py#L36

instead of here:

https://github.com/HSLdevcom/helmet-model-system/blob/f43f167ca5caae9aa2ee776e9b35c9b46d19a37f/Scripts/utils/calc_noise.py#L46

Then ´cross_traffic` would also be at least 0.01, which would prevent noise from going below zero.

2022-03-15 08:50 UTC, zptro commented on Scripts/utils/calc_noise.py
> +            raise ValueError("{}".format(link.id))
```suggestion
            raise ValueError("No noise interval found for link {}".format(link.id))
```

2022-04-01 10:46 UTC, zptro approved these changes

2022-04-04 07:07 UTC, johpiip commented
Nice! I forgot about this when I had to hurry assessments but great that you did not. :) Should we make a test run or did you do that already?

2022-04-04 11:42 UTC, zptro commented
> Nice! I forgot about this when I had to hurry assessments but great that you did not. :) Should we make a test run or did you do that already?

Yes, we should probably do a 2040 test run.

2022-04-14 09:28 UTC, johpiip commented
@zptro I tested this and it works! Those links which had a noise zone width of 5 still have it. Ve0 scenario does not crash when writing links.

2022-04-25 07:35 UTC, merged